# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: host.docker.internal # Points to the host machine from within Docker
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] || 'sim_card' %>
  password: <%= ENV['DB_PASSWORD'] || 'sim_card' %>
  database: <%= ENV['DB_NAME'] || 'sim_card' %>

development:
  <<: *default

test:
  <<: *default
  database: sim_card_test

production:
  <<: *default
  pool: 10
  timeout: 5000
